name: CI - Upload & Secrets

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Run pytest
        run: |
          python -m pytest -q

  detect-secrets:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v4
      - name: Install detect-secrets
        run: pip install detect-secrets
      - name: Scan for secrets
        run: |
          detect-secrets scan --update .secrets.baseline || true

  integration-upload:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install cloud deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_cloud.txt
      - name: Write client secrets temporarily
        env:
          VRP_CLIENT_SECRETS_JSON: ${{ secrets.VRP_CLIENT_SECRETS_JSON }}
        run: |
          echo "$VRP_CLIENT_SECRETS_JSON" > client_secrets.json
          chmod 600 client_secrets.json
      - name: Run integration smoke (only if secrets present)
        run: |
          python -c "print('Integration placeholder: would run a guarded smoke upload here')"
      - name: Cleanup
        run: |
          rm -f client_secrets.json 2>/dev/null || true
